backend:
  image: registry.relizahub.com/library/rebom-backend
  replicaCount: 1
  port: 4000
  targetPort: 4000
frontend:
  image: registry.relizahub.com/library/rebom-frontend
  replicaCount: 1
  port: 80
  targetPort: 80
postgresql:
  image: postgres:14.1
  defaultSecret: true
  replicaCount: 1
  storage: 5Gi
flyway:
  image: flyway/flyway:8.4.4-alpine
ingress:
  minimalIngressEnabled: true
  traefikEnabled: true
  host: $RELIZA{PROPERTY.FQDN}